### ISSUE TITLE
Crear tabla usuarios

### ISSUE THREAD

**Issue by dferps88** [DiegoMerchan/API_EPS#2]
Modelar la tabla de usuarios con la siguiente información

Nit de la EPS que realiza el registro (Númerico)
Nombre Completo del usuario (Alfanúmerico)
Número de Cedula (Númerico)
Estado de Vacunación (Alfanúmerico)

**Comment by DiegoMerchan** [comment]
Se definen los campos de la tabla de usuarios de vacunas.

**Comment by DiegoMerchan** [comment]
Se empieza la creación del script

**Comment by DiegoMerchan** [comment]
Base de datos creada en MySQL
