### ISSUE TITLE
Permitir La modificación de un usuario

### ISSUE THREAD

**Issue by dferps88** [DiegoMerchan/API_EPS#3]
Habilitar la edición de los datos de un usuario especificando

Nit de la EPS (Númerico)
Número de cedula (Alfanúmerico)
Parametro a modificar (cedula, nombre completo, estado de vacunación)

**Comment by DiegoMerchan** [comment]
Se define método de modificación de usuarios del servicio web

**Comment by DiegoMerchan** [comment]
API ya cuenta con esta funcionalidad
